### ISSUE TITLE
Patchwork tiering is a little weird

### ISSUE THREAD

**Issue by TDHooligan** [mw5mercs-modding/harjel#1]
Why does patchwork now mandate tier restrictions like Harjel? I understand why Harjel is restricted tier-wise as mixing and matching would just make T3 torsos-T1 small hitboxes the standard, but mandating the same level of Patchwork simply makes tier 1 patchwork the only one you want.
I'd suggest either buffing T2&3 Patchworks' slot efficiency or removing this tier restriction, as I think 0.14 patchworks were in a good place. 

edit: the slot efficiency increase is probably not even a great idea, considering how much dynamic filler is in the game.

**Comment by trueg** [comment]
I don't follow. I have not Changed patchwork. Also harjel has no tonnage restrictions...

**Comment by TDHooligan** [comment]
![image](https://user-images.githubusercontent.com/6061314/148667344-f4a1cf4f-4659-4a9a-86ef-27901be33853.png)
this is possible in 0.14, it is not in 0.15, as it doesnt let you mix T1 and T3 patchwork

if it's intentional, why would you ever want to use t2 or t3 patchworks when you can put multiple t1's in?

**Comment by trueg** [comment]
you are correct, i did change that... why I cannot remember. I guess I can simply revert it.

**Comment by trueg** [comment]
better balancing would be good indeed...

**Comment by trueg** [comment]
removed restrictions for 0.16 which will be released with the next YAML update

**Comment by TDHooligan** [comment]
0.16 looks good!
